spring:
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/prod?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 940930zsl
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.103
    port: 6379
    password: 0930zsl
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 #最大空闲连接
        min-idle: 1 #最小空闲连接
        max-wait: 100ms #连接等待时间
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: jojo
    password: 0930zsl
    # 设置发布确认
    # 若只设置此参数，交换机在接收到消息后就会立即发送确认消息（消息未成功发送到队列的情况，发送方无法得知）
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
        # 设置消费者一次拉取多少条消息，可用于消费贷限流
        prefetch: 10

logging:
  config: classpath:log4j2-spring.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml